# Generated by Django 4.0.1 on 2022-01-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmodels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='drive_unit',
            field=models.CharField(choices=[('Передний', 'Fwd'), ('Задний', 'Rwd'), ('Полный', 'Awd'), ('Неизвестно', 'Unknown')], default='Передний', max_length=30),
        ),
    ]
