# Generated by Django 4.0 on 2022-01-29 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carmodels', '0002_carmodel_price_alter_carmodel_drive_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='price',
            new_name='base_price',
        ),
    ]
