# Generated by Django 4.0 on 2022-02-28 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carmodels', '0003_rename_price_carmodel_base_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='main_photo',
        ),
        migrations.CreateModel(
            name='CarModelPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='car_models/')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carmodels.carmodel')),
            ],
        ),
    ]
