# Generated by Django 4.0 on 2022-03-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmodels', '0004_remove_carmodel_main_photo_carmodelphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='main_photo',
            field=models.ImageField(default=1, upload_to='car_models-main/'),
            preserve_default=False,
        ),
    ]
