# Generated by Django 4.0 on 2022-03-06 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carmodels', '0005_carmodel_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodelphoto',
            name='model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carmodels.carmodel'),
        ),
    ]
