# Generated by Django 4.0.1 on 2022-01-20 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0002_alter_car_vin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion', models.TextField(default='Заключение не предоставлено.')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('VIN', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='cars.car')),
                ('inspector', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
