# Generated by Django 4.0.1 on 2022-01-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_option', '0001_initial'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='add_option_id',
            field=models.ManyToManyField(default=0, to='add_option.AddOption'),
        ),
    ]
