# Generated by Django 4.0.1 on 2022-01-18 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carmodels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('VIN', models.PositiveBigIntegerField(default=11111111111111111, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('Реализация', 'For Sale'), ('Выстовочный образец', 'Expo'), ('Для тест-драйва', 'Testdrive'), ('Неизвестно', 'Unknown')], default='Реализация', max_length=50)),
                ('model_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='carmodels.carmodel')),
            ],
        ),
    ]
