# Generated by Django 4.0.1 on 2022-01-19 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='VIN',
            field=models.PositiveBigIntegerField(default=11111111111111111, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999999999999)]),
        ),
    ]
