# Generated by Django 4.0.1 on 2022-01-19 11:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_vin'),
        ('testdrive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='testdrive',
            name='datetime_gt_now',
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='VIN',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='cars.car'),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AddConstraint(
            model_name='testdrive',
            constraint=models.CheckConstraint(check=models.Q(('date_time__gt', datetime.datetime(2022, 1, 19, 14, 37, 26, 923443))), name='datetime_gt_now'),
        ),
    ]
