# Generated by Django 4.0 on 2022-02-19 10:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdrive', '0024_remove_testdrive_datetime_gt_now_alter_testdrive_vin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDriveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(' Заявка не согласована', 'Not Agreed'), ('Заявка согласована', 'Agreed'), ('Отменен', 'Canceled'), ('Проведен', 'Done')], default=' Заявка не согласована', max_length=100)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='testdrive',
            name='datetime_gt_now',
        ),
        migrations.AddConstraint(
            model_name='testdrive',
            constraint=models.CheckConstraint(check=models.Q(('date_time__gt', datetime.datetime(2022, 2, 19, 13, 6, 5, 622400))), name='datetime_gt_now'),
        ),
        migrations.AddField(
            model_name='testdrive',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='testdrive.testdrivestatus'),
        ),
    ]
