# Generated by Django 4.0 on 2022-02-19 11:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('testdrive', '0025_testdrivestatus_remove_testdrive_datetime_gt_now_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='testdrive',
            name='datetime_gt_now',
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='seller',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='employees.useraccount'),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='testdrive.testdrivestatus'),
        ),
        migrations.AddConstraint(
            model_name='testdrive',
            constraint=models.CheckConstraint(check=models.Q(('date_time__gt', datetime.datetime(2022, 2, 19, 14, 8, 40, 170284))), name='datetime_gt_now'),
        ),
    ]
