# Generated by Django 4.0 on 2022-02-22 06:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('testdrive', '0026_remove_testdrive_datetime_gt_now_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='testdrive',
            name='datetime_gt_now',
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='client_phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+{1}7{1}\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='seller',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.useraccount'),
        ),
    ]
