# Generated by Django 4.0 on 2022-03-01 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_carphoto'),
        ('employees', '0001_initial'),
        ('testdrive', '0027_remove_testdrive_datetime_gt_now_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdrive',
            name='VIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.car'),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='seller',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='employees.useraccount'),
        ),
        migrations.AlterField(
            model_name='testdrivestatus',
            name='name',
            field=models.CharField(choices=[('Заявка не согласована', 'Not Agreed'), ('Заявка согласована', 'Agreed'), ('Отменен', 'Canceled'), ('Проведен', 'Done')], default='Заявка не согласована', max_length=100),
        ),
    ]
