# Generated by Django 4.0 on 2022-02-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_option', '0002_addoption_desciption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addoption',
            old_name='desciption',
            new_name='description',
        ),
    ]
