# Generated by Django 4.0.1 on 2022-01-19 10:55

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import testdrive.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('client_name', models.CharField(max_length=255)),
                ('client_phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{11,11}$')])),
                ('VIN', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='cars.car', validators=[testdrive.models.validate_length])),
                ('seller', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='testdrive',
            constraint=models.UniqueConstraint(fields=('VIN', 'date_time'), name='unique_VIN_datetime'),
        ),
        migrations.AddConstraint(
            model_name='testdrive',
            constraint=models.CheckConstraint(check=models.Q(('date_time__gt', datetime.datetime(2022, 1, 19, 13, 55, 44, 121883))), name='datetime_gt_now'),
        ),
    ]
