# Generated by Django 4.0.1 on 2022-01-19 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdrive', '0002_remove_testdrive_datetime_gt_now_alter_testdrive_vin_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='testdrive',
            name='datetime_gt_now',
        ),
        migrations.AddConstraint(
            model_name='testdrive',
            constraint=models.CheckConstraint(check=models.Q(('date_time__gt', datetime.datetime(2022, 1, 19, 15, 0, 17, 118308))), name='datetime_gt_now'),
        ),
    ]
