# Generated by Django 4.0.1 on 2022-01-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_inspection', '0004_alter_techinspection_vin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techinspection',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
