# Generated by Django 4.0 on 2022-03-01 07:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('cars', '0014_carphoto'),
        ('tech_inspection', '0006_alter_techinspection_vin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techinspection',
            name='conclusion',
        ),
        migrations.AddField(
            model_name='techinspection',
            name='conclusion_file',
            field=models.FileField(null=True, upload_to='tech-inspection-conclusion/'),
        ),
        migrations.AlterField(
            model_name='techinspection',
            name='VIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.car', validators=[django.core.validators.RegexValidator('^(([(A-Z)*(\\d)*]){17}|([(\\d)*(A-Z)*]){17})$', 'VIN должен состоять из 17 заглавных букв и цифр.')]),
        ),
        migrations.AlterField(
            model_name='techinspection',
            name='inspector',
            field=models.ForeignKey(limit_choices_to=models.Q(('is_sales_director', True), ('is_tech_inspector', True), ('is_superuser', True), _connector='OR'), on_delete=django.db.models.deletion.DO_NOTHING, to='employees.useraccount'),
        ),
    ]
