# Generated by Django 4.0 on 2022-03-22 15:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('cars', '0016_alter_status_name'),
        ('tech_inspection', '0007_remove_techinspection_conclusion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechInspectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='techinspection',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('conclusion_file__isnull', True), ('end_date__isnull', True)), models.Q(('conclusion_file__isnull', False), ('end_date__isnull', False)), _connector='OR'), name='if_ended_than_attach_conclusion'),
        ),
        migrations.AddField(
            model_name='techinspectionrequest',
            name='VIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.car', validators=[django.core.validators.RegexValidator('^(([(A-Z)*(\\d)*]){17}|([(\\d)*(A-Z)*]){17})$', 'VIN должен состоять из 17 заглавных букв и цифр.')]),
        ),
        migrations.AddField(
            model_name='techinspectionrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.useraccount'),
        ),
        migrations.AddField(
            model_name='techinspection',
            name='request',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tech_inspection.techinspectionrequest'),
            preserve_default=False,
        ),
    ]
