# Generated by Django 4.0 on 2022-03-24 04:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_alter_car_vin'),
        ('tech_inspection', '0008_techinspectionrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='techinspectionrequest',
            name='reason',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='techinspection',
            name='VIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.car', validators=[django.core.validators.RegexValidator('^(?=.*?\\d)(?=.*?[A-Z])[A-Z\\d]{17}', 'VIN должен состоять из 17 заглавных букв и цифр.')]),
        ),
        migrations.AlterField(
            model_name='techinspectionrequest',
            name='VIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.car', validators=[django.core.validators.RegexValidator('^(?=.*?\\d)(?=.*?[A-Z])[A-Z\\d]{17}', 'VIN должен состоять из 17 заглавных букв и цифр.')]),
        ),
    ]
