# Generated by Django 4.0 on 2022-03-24 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech_inspection', '0009_techinspectionrequest_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techinspection',
            name='request',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tech_inspection.techinspectionrequest'),
        ),
    ]
