# Generated by Django 4.0 on 2022-03-26 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech_inspection', '0010_alter_techinspection_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techinspection',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tech_inspection.techinspectionrequest'),
        ),
    ]
