# Generated by Django 4.0 on 2022-03-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_inspection', '0014_remove_techinspection_if_ended_than_attach_conclusion_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='techinspection',
            name='if_ended_than_attach_conclusion',
        ),
    ]
