# Generated by Django 4.0 on 2022-03-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_inspection', '0016_techinspection_if_ended_than_attach_conclusion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='techinspection',
            name='if_ended_than_attach_conclusion',
        ),
    ]
