# Generated by Django 4.0.1 on 2022-01-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField()),
                ('body', models.CharField(choices=[('Седан', 'Sedan'), ('Хэтчбек 3 дв.', 'Hatchback 3'), ('Хэтчбек 5 дв.', 'Hatchback 5'), ('Лифтбек', 'Liftback'), ('Внедорожник 3 дв.', 'Suv 3'), ('Внедорожник 5 дв.', 'Suv 5'), ('Универсал', 'Sw'), ('Купе', 'Coupe'), ('Минивэн', 'Minivan'), ('Пикап', 'Pickup Truck'), ('Лимузин', 'Limousine'), ('Фургон', 'Van'), ('Кабриолет', 'Cabriolet'), ('Неизвестно', 'Unknown')], default='Седан', max_length=30)),
                ('engine_volume', models.DecimalField(decimal_places=2, max_digits=3)),
                ('engine_power', models.PositiveSmallIntegerField()),
                ('fuel_type', models.CharField(choices=[('Бензин', 'Petrol'), ('Дизель', 'Diesel'), ('Гибрид', 'Hybrid'), ('Электро', 'Electro'), ('Неизвестно', 'Unknown')], default='Бензин', max_length=30)),
                ('transmission_type', models.CharField(choices=[('Автоматическая', 'Automatic'), ('Робот', 'Robot'), ('Вариатор', 'Variator'), ('Механическая', 'Manual'), ('Неизвестно', 'Unknown')], default='Автоматическая', max_length=30)),
                ('drive_unit', models.CharField(choices=[('Передний', 'Fwd'), ('Задний', 'Rwd'), ('ПОЛНЫЙ', 'Awd'), ('Неизвестно', 'Unknown')], default='Передний', max_length=30)),
                ('package_name', models.CharField(max_length=255)),
                ('package_descr', models.TextField(default='Подробное описание комплектации не найдено.')),
                ('main_photo', models.ImageField(upload_to='car_models/')),
                ('model_descr', models.TextField(default='Подробное описание модели не найдено.')),
            ],
        ),
    ]
