# Generated by Django 4.0.1 on 2022-01-20 05:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0002_alter_car_vin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('add_option', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Покупка единовременным платежом', 'Full Price'), ('Покупка в кредит', 'Credit'), ('Покупка по программе трейд-ин', 'Trade In')], default='Покупка единовременным платежом', max_length=100)),
                ('coefficient', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('customer_passport', models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('VIN', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='cars.car')),
                ('add_option_id', models.ManyToManyField(null=True, to='add_option.AddOption')),
                ('purchase_type_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='sale.purchasetype')),
                ('seller', models.ForeignKey(default=0, limit_choices_to={'is_sales_director': True, 'is_sales_manager': True}, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
