# Generated by Django 4.0 on 2022-02-05 14:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_vin'),
        ('sale', '0009_alter_sale_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='VIN',
            field=models.ForeignKey(default='A0000000000000000', on_delete=django.db.models.deletion.SET_DEFAULT, to='cars.car', validators=[django.core.validators.RegexValidator('^(([(A-Z)*(\\d)*]){17}|([(\\d)*(A-Z)*]){17})$', 'VIN должен состоять из 17 заглавных букв и цифр.')]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_passport',
            field=models.CharField(max_length=10, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.RegexValidator('^([(\\d)+]){10}$', 'Серия и номер пасспорта должны состоять из 10 цифр.')]),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(check=models.Q(('customer_passport__length', 10)), name='passport_length'),
        ),
    ]
