# Generated by Django 4.0 on 2022-02-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0010_alter_sale_vin_alter_sale_customer_passport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='note',
            field=models.TextField(blank=True, default='Примечание продажи не указано.', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
