# Generated by Django 4.0 on 2022-02-16 05:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0012_alter_sale_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer_passport',
            field=models.CharField(max_length=10, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)]),
        ),
    ]
