# Generated by Django 4.0 on 2022-02-17 06:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_option', '0003_rename_desciption_addoption_description'),
        ('cars', '0009_alter_car_vin'),
        ('sale', '0020_alter_sale_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='VIN',
            field=models.ForeignKey(default='A0000000000000000', on_delete=django.db.models.deletion.SET_DEFAULT, to='cars.car', validators=[django.core.validators.RegexValidator('^(?=.*?\\d)(?=.*?[A-Z])[A-Z\\d]{17}')]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='add_option_id',
            field=models.ManyToManyField(blank=True, default=0, to='add_option.AddOption'),
        ),
    ]
