# Generated by Django 4.0 on 2022-03-01 10:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('cars', '0014_carphoto'),
        ('sale', '0021_alter_sale_vin_alter_sale_add_option_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Совершена', 'Commited'), ('Отменена', 'Canceled')], default='Совершена', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SaleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Обычная продажа', 'Standard'), ('Предзаказ', 'Preorder')], default='Обычная продажа', max_length=100)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='sale',
            name='passport_length',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer_passport',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='purchase_type_id',
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_info',
            field=models.TextField(default='Информация о покупателе не указана.'),
        ),
        migrations.AddField(
            model_name='sale',
            name='purchase_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sale.purchasetype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='VIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.car', validators=[django.core.validators.RegexValidator('^(?=.*?\\d)(?=.*?[A-Z])[A-Z\\d]{17}')]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(limit_choices_to=models.Q(('is_sales_director', True), ('is_sales_manager', True), ('is_superuser', True), _connector='OR'), on_delete=django.db.models.deletion.DO_NOTHING, to='employees.useraccount'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sale.salestatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sale.saletype'),
            preserve_default=False,
        ),
    ]
