# Generated by Django 4.0 on 2022-03-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0022_salestatus_saletype_remove_sale_passport_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_document',
            field=models.FileField(default=1, upload_to='sale-documents/'),
            preserve_default=False,
        ),
    ]
