# Generated by Django 4.0 on 2022-03-27 11:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_alter_car_vin'),
        ('sale', '0023_sale_sale_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='VIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.car', validators=[django.core.validators.RegexValidator('^(?=.*?\\d)(?=.*?[A-Z])[A-Z\\d]{17}', 'VIN должен состоять из 17 заглавных букв и цифр.')]),
        ),
    ]
