# Generated by Django 4.0.1 on 2022-01-18 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalType',
            fields=[
                ('arrival_type_id', models.PositiveSmallIntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Новый', 'New'), ('С пробегом', 'Has Millage'), ('Трейд-ин', 'Trade In'), ('Возврат', 'Returned'), ('После ремонтных работ', 'After Repair'), ('Неизвестно', 'Unknown')], default='Новый', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_value', models.DecimalField(decimal_places=2, max_digits=11)),
                ('millage', models.PositiveIntegerField()),
                ('VIN', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='cars.car')),
                ('arrival_type_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='stock.arrivaltype')),
            ],
        ),
    ]
