# Generated by Django 4.0 on 2022-02-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stock_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='arrival_date',
            field=models.DateField(null=True),
        ),
    ]
