# Generated by Django 4.0 on 2022-02-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stock_arrival_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='arrival_date',
            field=models.DateField(),
        ),
    ]
