# Generated by Django 4.0 on 2022-03-06 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('stock', '0006_rename_arrival_type_id_stock_arrival_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='acceptor',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(('is_sales_director', True), ('is_puchase_manager', True), ('is_superuser', True), _connector='OR'), on_delete=django.db.models.deletion.DO_NOTHING, to='employees.useraccount'),
            preserve_default=False,
        ),
    ]
