# Generated by Django 4.0 on 2022-03-27 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('stock', '0007_stock_acceptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='acceptor',
            field=models.ForeignKey(limit_choices_to=models.Q(('is_sales_director', True), ('is_puchase_manager', True), _connector='OR'), on_delete=django.db.models.deletion.DO_NOTHING, to='employees.useraccount'),
        ),
    ]
