# Generated by Django 4.0 on 2022-02-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='note',
            field=models.TextField(blank=True, default='Примечание не найдено.', null=True),
        ),
    ]
