# Generated by Django 4.0 on 2022-02-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='VIN',
            field=models.CharField(max_length=17, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.CheckConstraint(check=models.Q(('VIN__length__exact', 17)), name='VIN_legth'),
        ),
    ]
