# Generated by Django 4.0 on 2022-02-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_vin_car_vin_legth'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='car',
            name='VIN_legth',
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.CheckConstraint(check=models.Q(('VIN__length__gt', 16), ('VIN__length__lt', 18)), name='VIN_length'),
        ),
    ]
