# Generated by Django 4.0 on 2022-02-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_remove_car_vin_legth_car_vin_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='car',
            name='VIN_length',
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.CheckConstraint(check=models.Q(('VIN__length', 17)), name='VIN_length'),
        ),
    ]
