# Generated by Django 4.0 on 2022-02-05 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_remove_car_vin_length_car_vin_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='VIN',
            field=models.CharField(max_length=17, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^(([(A-Z)*(\\d)*]){17}|([(\\d)*(A-Z)*]){17})$', 'VIN должен состоять из 17 заглавных букв и цифр.')]),
        ),
    ]
