# Generated by Django 4.0 on 2022-02-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_vin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Реализация', 'For Sale'), ('Выстовочный образец', 'Expo'), ('Для тест-драйва', 'Testdrive'), ('Неизвестно', 'Unknown')], default='Реализация', max_length=100)),
            ],
        ),
    ]
