# Generated by Django 4.0 on 2022-02-20 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='purpose',
        ),
    ]
