# Generated by Django 4.0 on 2022-02-20 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_remove_car_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='purpose',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='cars.purpose'),
        ),
    ]
