# Generated by Django 4.0 on 2022-03-01 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_car_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('В наличии', 'In Stock'), ('На техосмотре', 'Tech Inspection'), ('На техоблуживании', 'Tech Maintenance'), ('Продан', 'Sold'), ('Неизвестно', 'Unknown')], default='Неизвестно', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='note',
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, default='Описание не найдено.', null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='purpose',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='cars.purpose'),
        ),
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, to='cars.status'),
        ),
    ]
