# Generated by Django 4.0 on 2022-03-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_carphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='note',
            field=models.TextField(blank=True, default='Примечание не найдено.', null=True),
        ),
    ]
