# Generated by Django 4.0 on 2022-03-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_car_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('В наличии', 'In Stock'), ('На техосмотре', 'Tech Inspection'), ('На техоблуживании', 'Tech Maintenance'), ('Продан', 'Sold'), ('Проходит приемку', 'Acceptance'), ('Неизвестно', 'Unknown')], default='Неизвестно', max_length=100),
        ),
    ]
