# Generated by Django 4.0 on 2022-03-24 04:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='VIN',
            field=models.CharField(max_length=17, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^(?=.*?\\d)(?=.*?[A-Z])[A-Z\\d]{17}', 'VIN должен состоять из 17 заглавных букв и цифр.')]),
        ),
    ]
